name = "titan-core-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
DATABASE_URL = "file:./titan.db"
JWT_SECRET = "titan-ultra-secret-key-change-in-prod"
ADMIN_ID = "0"

[[kv_namespaces]]
binding = "USER_DB"
id = "dummy-id-for-local-dev"

[site]
bucket = "./public"
